"""Run AI tests with a real runtime-settings.lua generated by the launcher.

Used by runtime_settings_integration_test.ps1; requires the existing test-only
Lupa dependency described in run_native_lua.py.
"""
import argparse
import os
from pathlib import Path
import sys

project = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(project / "work" / "lua-test-python"))
from lupa.lua51 import LuaRuntime

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--fixture", type=Path, required=True)
args = parser.parse_args()
fixture = args.fixture.resolve(strict=True)
os.chdir(project / "src" / "ai")
lua = LuaRuntime(unpack_returned_tuples=True)
lua.globals().RUNTIME_SETTINGS_FIXTURE = str(fixture)
lua.globals().dofile(str(project / "tests" / "player_settings_lua_test.lua"))
